CREATE TABLE IF NOT EXISTS users(
    id INT(255) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) UNIQUE NOT NULL,
	email VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL,
	role VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS elections(
	id INT(255) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	start DATETIME,
	stop DATETIME
);

CREATE TABLE IF NOT EXISTS candidates(
	id INT(255) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	nr_election INT(255),
	candidate VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS votes(
	id INT(255) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	voter VARCHAR(255),
	elected VARCHAR(255),
	vote_date DATETIME
);